[[redirects]]
from = "http://mazesprinttriad.com/*"
to = "https://mazesprinttriad.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.mazesprinttriad.com/*"
to = "https://mazesprinttriad.com/:splat"
status = 301
force = true
